// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]

export type Essay = Collections['essays']['schema']['_output']
export declare const essays: Essay[]
